### PR TITLE
Render Method & PettingZoo API

### PR DESCRIPTION
**Pull request by rodrigodelazcano**
The purpose of this PR is to add the following capabilities to the smac repository:

- Render method that allows visualization of the environment at real time. Developed with pygame 2.0.0 and pysc2 interface.
- Environment wrapper to allow compatibility with [PettingZoo API ](https://www.pettingzoo.ml/)

First of all, the render method shows the actions of the agents in each step in a simplified 2D pygame window. The render shows the map height, unit team, type, and health. As well as, the number of steps and score for each episode in the upper right of the window. This method is useful for visualization purposes and debugging.

Second, PettingZoo is a universal Python API with a variety of multi-agent environments. PettingZoo was developed with the goal of accelerating research in Multi-Agent Reinforcement Learning ("MARL"), by making work more interchangeable, accessible and reproducible akin to what OpenAI's Gym library did for single-agent reinforcement learning. PettingZoo's API, while inheriting many features of Gym, is unique amongst MARL APIs in that it's based around the novel [Agent Environment Cycle](https://arxiv.org/abs/2009.13051) ("AEC") games model. In this PR it is included a wrapper that creates a PettingZoo environment from the StarCraft2Env smac base environment. This feature will allow  the increasing number of user of PettingZoo API to benefit from the smac environment and vice versa.

The render method has been tested with the smac environment in the file [random_agents.py](https://github.com/rodrigodelazcano/smac/blob/master/smac/examples/random_agents.py). While an example of a PettingZoo environment played as an AEC game can be tested with the file [random_demo.py](https://github.com/rodrigodelazcano/smac/blob/master/smac/examples/pettingzoo/random_demo.py). The arguments for initializing the sc2 PettingZoo environment are the same as for the smac environment except for an additional one , `max_cycles`, which specifies the number of frames (a step for each agent) until game terminates.

A final example of the render method visualization using the PettingZoo environment wrapper in the "2c_vs_64zg" map is shown bellow.

I hope you find these new features interesting and thank you for your time,

Rodrigo

render_smac

### CODE REVIEW

**Comment by KaleabTessera** [comment]
This is a really great feature! Looking forward to having this merged in :)

**Comment by rodrigodelazcano** [comment]
> This is a really great feature! Looking forward to having this merged in :)

Thank you Kaleab! I am glad you liked it!!

**Review by samvelyan — CHANGES_REQUESTED** [review]
HI @rodrigodelazcano . Thanks again for your contribution. This looks great.

Would you mind also adding information on how to install pettingzoo and run the demo? I think a new Markdown file in `smac/examples/petttingzoo` would be very helpful (see the RLlib example there). I'll also refer to that file from the main REAME.

I've also added some additional (minor) change requests below.

**Comment by rodrigodelazcano** [comment]
Hi Mikayel! Thank you so much for taking your time to review the code. I think now it should be all set. Please let me know if you need anything else. Thanks again!

**Comment by samvelyan** [comment]
Hey @rodrigodelazcano . I've merged this branch through another PR https://github.com/oxwhirl/smac/pull/77 (with some minor changes).

Thank you again for this amazing contribution! 🙌

**Comment by rodrigodelazcano** [comment]
Thank you for the merge @samvelyan!!! I just have a small  doubt. Is it possible to appear as a contributor to the repo?

**Comment by samvelyan** [comment]
Oh, apparently you weren't added automatically because I squash-merged. I can add in the Readme file that you added the PettingZoo API and rendering, if you want.

**Comment by rodrigodelazcano** [comment]
No problem at all. My fault for working on the master branch. Yes that
would be great if possible, I can answer any questions related to those
topics. You can add my github account as a link.

Thanks

**Comment by samvelyan** [comment]
I was able to override the author of 9b73622 commit. Now you're a contributor!

**Comment by rodrigodelazcano** [comment]
Thank you so much Mikayel! :)

**Comment by samvelyan** [comment]
Of course! Also added info in the README.

**Pull request closed without merging**
