### PR TITLE
fixed pettingzoo wrapper to comply with PZ==1.13.1 api

### PR DESCRIPTION
**Pull request by benblack769**
Updates/fixes smac pettingzoo wrapper to comply with recent versions of gym and pettingzoo.

Replaces #81, see that PR for more comment. @KaleabTessera

### CODE REVIEW

**Comment by samvelyan** [comment]
CC @rodrigodelazcano

**Comment by rodrigodelazcano** [comment]
Yes, this can be merged. Thank you very much @benblack769

**Comment by KaleabTessera** [comment]
Yep, happy my side as well. Thanks @benblack769 👍

**Review by samvelyan — APPROVED** [review]
Looks good to me

**Comment by samvelyan** [comment]
Thanks a lot @benblack769 as well as @KaleabTessera and @rodrigodelazcano. Merging this and closing https://github.com/oxwhirl/smac/pull/81.

**Pull request merged**
